import os

DEBUG = True
THREADED = True
PATH_SYSTEM = os.getcwd()
ABSOLUTE_PATH = "."

POSTGRESQL_HOST = "159.203.2.249"
POSTGRESQL_USER = "postgres"
POSTGRESQL_PASSWORD = "xDsf1234!!s"
POSTGRESQL_DATABASE = "project"
POSTGRESQL_PORT = 5432

STOP_STANDARD = 0.1
